name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Run build
      run: ./scripts/build-switch.sh

    - name: Upload Moonlight-Switch.nro
      uses: actions/upload-artifact@master
      with:
        name: Moonlight-Switch
        path: Moonlight-Switch.nro
